## Netlify configuration (valid TOML)

[build]
  command = "npm run build"
  # Vite يضع index.html مباشرة داخل dist لذا يجب أن تكون مجلد النشر هو dist
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Increase resources for uploads
  external_node_modules = [
    "@supabase/supabase-js", 
    "multer", 
    "bcryptjs", 
    "express", 
    "express-session",
    "drizzle-orm",
    "@neondatabase/serverless",
    "postgres"
  ]
  included_files = ["server/**", "shared/**", "netlify/functions/**"]

[functions."api"]
  timeout = 26
  memory = 1024

## Local dev server config
[dev]
  command = "vite"            # start Vite dev server (config has root=client)
  targetPort = 5173            # Vite default
  port = 8888                  # Netlify Dev proxy port
  autoLaunch = false

## Proxy API requests to the `api` function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

## SPA fallback must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
