## Netlify configuration (valid TOML)

[build]
  command = "npm run build"
  publish = "dist/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

## Local dev server config
[dev]
  command = "vite"            # start Vite dev server (config has root=client)
  targetPort = 5173            # Vite default
  port = 8888                  # Netlify Dev proxy port
  autoLaunch = false

## Proxy API requests to the `api` function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200

## SPA fallback must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
