databases:
  - name: accounting-db
    databaseName: accounting_system
    user: accounting_user
    region: frankfurt # أقرب منطقة للشرق الأوسط

services:
  - type: web
    name: arabic-accounting-system
    runtime: node
    region: frankfurt
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: accounting-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    autoDeploy: true # نشر تلقائي من GitHub